name: Build and Deploy to Lambda S3

on:
  push:
    branches:
      - develop
    paths:
      - "workers/whatsapp/message-receiver-worker/**"
      - ".github/workflows/message-receiver-worker.yml"

  pull_request:
    branches:
      - develop
    paths:
      - "workers/whatsapp/message-receiver-worker/**"
      - ".github/workflows/message-receiver-worker.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'

      - name: Run build script
        run: |
          rm -rf dist
          tsc
          cp package.json dist/
          cd dist && npm install --omit=dev
          zip -r message-receiver-worker.zip .

      - name: Upload message-receiver-worker.zip to S3
        uses: aws-actions/aws-s3-sync-action@v1.0.0
        with:
          bucket: money-tracker-lambda-bucket
          region: us-west-1
          source-dir: ./dist/message-receiver-worker.zip
          destination-dir: s3://money-tracker-lambda-bucket/
